version: '3.9'

services:
  subscription-api:
    build: .
    ports:
      - "${PORT}:8080"
    env_file:
      - .env
    depends_on:
      - db
      - migrate
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "${DB_PORT}:5432"
    restart: unless-stopped

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    env_file:
      - .env
    depends_on:
      - db
    restart: "on-failure"

volumes:
  db_data:
