CREATE USER myuser WITH PASSWORD '123';
CREATE DATABASE subscription_service OWNER myuser;

\c subscription_service;

CREATE SCHEMA infosub AUTHORIZATION myuser;

GRANT USAGE ON SCHEMA infosub TO myuser;
GRANT CREATE ON SCHEMA infosub TO myuser;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA infosub TO myuser;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA infosub TO myuser;

ALTER DEFAULT PRIVILEGES IN SCHEMA infosub GRANT ALL ON TABLES TO myuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA infosub GRANT ALL ON SEQUENCES TO myuser;

GRANT ALL PRIVILEGES ON DATABASE subscription_service TO myuser;