basePath: /api/subscriptions
definitions:
  models.MidwaySub:
    properties:
      end_date:
        type: string
      id:
        type: integer
      price:
        type: integer
      service_name:
        type: string
      start_date:
        type: string
      user_id:
        type: string
    type: object
  models.Subscription:
    properties:
      end_date:
        type: string
      id:
        type: integer
      price:
        type: integer
      service_name:
        type: string
      start_date:
        type: string
      user_id:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API для управления подписками пользователей
  title: Subscription Service API
  version: "1.0"
paths:
  /{id}:
    delete:
      parameters:
      - description: ID записи
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Сообщение об успешном удалении
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Неверный ID
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Ошибка при удалении
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Удалить запись подписки по ID
      tags:
      - subscriptions
      - subscriptions-delete
    get:
      parameters:
      - description: ID записи
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Subscription'
        "400":
          description: Неверный формат ID
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Ошибка при получении данных
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Получить запись подписки по ID
      tags:
      - subscriptions
      - subscriptions-get
    put:
      consumes:
      - application/json
      parameters:
      - description: ID записи
        in: path
        name: id
        required: true
        type: integer
      - description: Данные для обновления
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/models.MidwaySub'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Subscription'
        "400":
          description: Неверный запрос
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Ошибка при обновлении
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Обновить запись подписки по ID
      tags:
      - subscriptions
      - subscriptions-put
  /all:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Subscription'
            type: array
        "500":
          description: Ошибка при получении данных
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Получить все записи подписок
      tags:
      - subscriptions
      - subscriptions-get
  /newrecord:
    post:
      consumes:
      - application/json
      parameters:
      - description: Данные подписки
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/models.MidwaySub'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Subscription'
        "400":
          description: Неверный запрос
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Ошибка при сохранении
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Создать новую запись подписки
      tags:
      - subscriptions
      - subscriptions-post
  /service/{name}:
    delete:
      parameters:
      - description: Название сервиса
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Сообщение об успешном удалении
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Подписки не найдены
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Удалить все записи подписок по имени сервиса
      tags:
      - subscriptions
      - subscriptions-delete
    get:
      parameters:
      - description: Название сервиса
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Subscription'
            type: array
        "404":
          description: Подписки не найдены
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Получить подписки по имени сервиса
      tags:
      - subscriptions
      - subscriptions-get
  /summary:
    get:
      parameters:
      - description: 'Начало периода (формат: MM-YYYY)'
        in: query
        name: from
        required: true
        type: string
      - description: 'Конец периода (формат: MM-YYYY)'
        in: query
        name: to
        required: true
        type: string
      - description: UUID пользователя
        in: query
        name: user_id
        type: string
      - description: Название сервиса
        in: query
        name: service_name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: total_cost и список подписок
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Неверные параметры
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Ошибка при получении данных
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Получить сводку подписок за период
      tags:
      - subscriptions
      - subscriptions-filter
  /user/{id}:
    delete:
      parameters:
      - description: UUID пользователя
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Сообщение об успешном удалении
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Неверный UUID
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Подписки не найдены
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Удалить все записи подписок пользователя по его UUID
      tags:
      - subscriptions
      - subscriptions-delete
    get:
      parameters:
      - description: UUID пользователя
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Subscription'
            type: array
        "400":
          description: Неверный UUID
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Подписки не найдены
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Получить подписки пользователя по ID
      tags:
      - subscriptions
      - subscriptions-get
swagger: "2.0"
